### ISSUE TITLE
자유게시판 DB 매칭

### ISSUE THREAD

**Issue by kmr5259** [choi-hyuk-jin/festival#3]
**자유게시판**
BOARD_SEQ -> board_num 게시글번호
BOARD_RE_REF -> fb_group_num 글의 그룹 번호
BOARD_RE_LEV -> 삭제 답변 글의 깊이
BOARD_RE_SEQ -> 삭제 답변 글의 순서
BOARD_WRITER -> m_nickname 작성자명
BOARD_SUBJECT -> fb_title 게시글 제목
BOARD_CONTENT -> fb_content 게시글 내용
BOARD_HITS ->fb_hits 조회수
DEL_YN -> fb_delete_yn 삭제 유무
INS_USER_ID -> m_id 아이디(비로그인시 null)
INS_DATE -> fb_insert_date 작성일
UPD_USER_ID -> 삭제 수정자 id
UPD_DATE -> fb_update_date 수정일
PRIMARY KEY (BOARD_SEQ)->(board_num)

**Comment by choi-hyuk-jin** [comment]
BOARD_RE_LEV-> 삭제 답변 글의 깊이
BOARD_RE_SEQ-> 삭제 답변 글의 순서
UPD_USER_ID-> 삭제 수정 자 id
 이렇게 삭제네요
